# Generated by Django 3.2 on 2023-05-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_tagingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagIngredient',
        ),
    ]
