# Generated by Django 3.2 on 2023-05-08 15:12

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20230507_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 8, 15, 12, 21, 618818, tzinfo=utc), verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
