# Generated by Django 3.2 on 2023-05-08 15:24

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_recipe_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 5, 8, 15, 24, 2, 386675, tzinfo=utc), upload_to='recipes/images/'),
            preserve_default=False,
        ),
    ]
