# Generated by Django 3.2 on 2023-05-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('user',)},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('ingredient__name',)},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('user',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes/images/', verbose_name='Картинка'),
        ),
    ]
